{% set name = "django-auditlog" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-auditlog-{{ version }}.tar.gz
  sha256: 9de49f80a4911135d136017123cd73461f869b4947eec14d5e76db4b88182f3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2
    - python-dateutil >=2.7.0

test:
  imports:
    - auditlog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jazzband/django-auditlog
  summary: Audit log app for Django
  dev_url: https://github.com/jazzband/django-auditlog
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
